language: python
python:
  - "2.6"
env:
  - DJANGO_VERSION=1.4
#Command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
#Command to run tests
script:
  - KEY="'_$mfn4it@819%gjc$c*uo$_##_(kc9m0pjk==-^z4y(1alef8r'"
  - sed 's/'"SECRET_KEY = ''"'/'"SECRET_KEY = $KEY"'/g' inv/inv/local_settings.py.template > inv/inv/local_settings.py
  - cp inv/inv/local_settings.py inv/inv/local_settings.py.template
  - sed 's/'"'ENGINE': 'django.db.backends.'"'/'"'ENGINE': 'django.db.backends.sqlite3'"'/g' inv/inv/local_settings.py.template > inv/inv/local_settings.py
  - cp inv/inv/local_settings.py inv/inv/local_settings.py.template
  - sed 's/'"'NAME': ''"'/'"'NAME': 'database'"'/g' inv/inv/local_settings.py.template > inv/inv/local_settings.py
  - python inv/manage.py test
