language: python
python:
  - "2.6"
env:
  - DJANGO_VERSION=1.4.5
#Command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
#Command to run tests
script:
  - mkdir logs
  - cp inv/inv/local_settings.py.template inv/inv/local_settings.py
  - cd inv
  - python manage.py test invapp
# Email notifications
notifications:
    email:
      - darshan@email.gwu.edu
      - dchud@email.gwu.edu
      - jngomez@email.gwu.edu
