language: python
python:
  - "2.6"
env:
  - DJANGO_VERSION=1.4
#Command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
#Command to run tests
script:
  - cp inv/inv/local_settings.py inv/inv/local_settings.py.template
  - python inv/manage.py test
