language: python
python:
  - "2.6"
env:
  - DJANGO_VERSION=1.4
  - SECRET_KEY="_$mfn4it@819%gjc$c*uo$_##_(kc9m0pjk==-^z4y(1alef8r"
#Command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
#Command to run tests
script:
  - sed 's/'"SECRET_KEY = ''"'/'"SECRET_KEY = $SECRET_KEY"'/g' local_settings.py.template > local_settings.py
  - python inv/manage.py test
