language: python
python:
  - "2.6"
#Command to install dependencies
install: "pip install -r requirement.txt --use-mirrors"
#Command to run tests
script:
  - python manage.py test
env:
  - DJANGO=1.4
