from django.contrib import admin
from invapp.models import *

admin.site.register(Entity)
admin.site.register(Collection)
admin.site.register(Item)
admin.site.register(Copy)
admin.site.register(Machine)
admin.site.register(Address)
admin.site.register(Server)
admin.site.register(OfflineStorage)
admin.site.register(Actor)
admin.site.register(Person)
admin.site.register(System)
admin.site.register(Organization)
admin.site.register(Action)
admin.site.register(Project)
#admin.site.register(ReformattingProject)
#admin.site.register(ImageReformattingProject)
admin.site.register(BookScanningProject)
admin.site.register(MicrofilmScanningProject)
admin.site.register(LoosePaperScanningProject)
admin.site.register(AudioReformattingProject)
admin.site.register(VideoReformattingProject)
